name: learn-github-actions
on: [push]
jobs:
  add-code:
    runs-on: ubuntu:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }} has been cloned."
